# Generated by Django 2.1.5 on 2019-02-07 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=255)),
                ('customerUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.IntegerField()),
                ('customerPayment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentCategory', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productCategory', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productType',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='website.ProductType'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='paymentName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.PaymentType'),
        ),
        migrations.AddField(
            model_name='order',
            name='Product',
            field=models.ManyToManyField(through='website.ProductOrder', to='website.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='customerOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.PaymentMethod'),
        ),
    ]
